name: math_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  flutter_riverpod: ^2.4.1
  pinput: ^3.0.1
  flutter_native_splash: ^2.3.2
  image: ^4.1.3

flutter_native_splash:
  color: "#ffffff"
  image: assets/marinin.jpg
  android_12:
    image: assets/marinin.jpg

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
